[workspace]
resolver = "2"
members = [
    "crates/mersey_front",
    "crates/mersey_interp",
    "crates/mersey_cli",
    "crates/mersey_wasm",
    "crates/mersey_jit",
    "crates/mersey_capi",
    "crates/mersey_fuzz",
    "crates/mersey_js",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"
