[package]
name = "mersey_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The mersey command-line tool"

[[bin]]
name = "mersey"
path = "src/main.rs"

[dependencies]
mersey_front = { path = "../mersey_front" }
mersey_js = { path = "../mersey_js" }
mersey_interp = { path = "../mersey_interp" }
mersey_jit = { path = "../mersey_jit" }
ureq = { version = "3", default-features = false, features = ["rustls"] }

[lints]
workspace = true
